@baseUrl = http://localhost:3333

# @name Create account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@example.com",
    "password": "123456"
}

###

# @name Authentication
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@example.com",
    "password": "123456"
}
