@baseUrl = http://localhost:3333
@authToken = {{Authentication.response.body.access_token}}

# @name Authentication
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "johndoe@example.com",
    "password": "123456"
}

###
# @name CreateAccount
POST {{baseUrl}}/accounts
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@example.com",
    "password": "123456"
}

###
# @name CreateQuestion
POST {{baseUrl}}/questions
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "New question",
    "content": "Question content"
}



