version: '3.8'

services:
  postgres:
    container_name: database-pg
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres 
    volumes:
      - ./data/postgres:/data/postgres